# subprocess_run_check.py

_____ ?

try:
    ?.r..(['false'], check_True)
except ?.CalledProcessError as err:
    print('ERROR:', err)

# $ python3 subprocess_run_check.py
#
# ERROR: Command '['false']' returned non-zero exit status 1



